version: "3.9"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - .:/app:delegated
    command: bash -lc "python manage.py migrate --noinput && python manage.py runserver 0.0.0.0:8000"
