version: "3.9"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: auth_demo_api
    env_file:
      - .env
    command: ./entrypoint.sh
    ports:
      - "8000:8000"
    volumes:
      - .:/app:delegated 
